### ISSUE TITLE
mark transient, and other enhancements

### ISSUE THREAD

**Issue by bgschiller** [CGenie/alfred-pass#14]
Thank you very much for your plugin. I've been using it for a couple of years now, and it's an important part of my workflow.

I did have to make a few tweaks to get it to run correctly on my machine though. It might be worth documenting, or incorporating these changes:

- If you have a passphrase on your gpg key, passwords will fail to decrypt. I found that this is because there's no terminal available to type in my password to unlock the gpg key. I fixed this by changing my pinentry program to `pinentry-mac`.
- I still prefer to use the ncurses pinentry program when in the terminal, so I wrote a wrapper that dispatches to the right one depending on whether `pass` is being called directly or by `show-pass.sh`.
- Using the `-c` flag caused me to be unable to run the plugin more frequently than every 45 seconds. Presumably because the `show-pass.sh` process hadn't exited yet. Instead, I removed `-c` and used Alfred to copy the item to my history. This also fixed the next item.
- I use Alfred's clipboard history feature, and didn't like that my passwords were being logged for several days in that history. By using Alfred's "mark item as transient", this insecurity is avoided.

Here's what my flowchart looks like now:
![](https://trello-attachments.s3.amazonaws.com/58d428743111af1d0a20cf28/5b3c500597a94a30ab6908dd/d94a9111c0efeb4933522e53bd00781e/capture.png)

The red path is if the script failed to produce any output, in which case we show an error message. The green path is when there *was* output, so we copy it to the clipboard and show a notification. Leveraging Alfred to copy to clipboard, instead of pbcopy, means we are able to make the data as "transient" and it isn't recorded in our clipboard history.

These changes are documented on my blog at https://brianschiller.com/blog/2016/08/31/gnu-pass-alfred

Please let me know if you'd like me to prepare a pull request with any of these items.

**Comment by CGenie** [comment]
Brilliant, thank you for the remarks, I'll try to incorporate your changes as it seems to be a great improvement. I like the transient feature much.
I basically work with this day-to-day and I have the passwords in the keychain so I didn't even notice the error about password not present anymore.

**Comment by lilyinstarlight** [comment]
I've attempted to implement something like this in fkmclane/alfred-pass@ c828cf43470f7f209c0b324bd5b15b1b725d1ba3 (bgschiller branch).

**Comment by dgrabla** [comment]
Was the transient feature already merged? What is the most updated fork with the transient feature?

**Comment by CGenie** [comment]
Merged finally, sorry for the long time, I'm not using a Mac for work anymore :)

**Comment by dgrabla** [comment]
Great thanks!
In case it helps somebody: remember you still need to tick the "mark item as transient in clipboard" as it is not ticket by default when updating / maybe it is when installing from scratch.
![image](https://user-images.githubusercontent.com/1942073/52212815-a9749380-288d-11e9-9d29-ec66ec03f3c3.png)

**Comment by CGenie** [comment]
Ah my bad, I didn't tick that checkbox :)

**Comment by CGenie** [comment]
OK merged a fix in https://github.com/CGenie/alfred-pass/pull/22
